library(tibble)
library(dplyr)
library(tidyr)
colnames <- read.table('UCI HAR Dataset/features.txt',stringsAsFactors = FALSE)
test <- read.table('UCI HAR Dataset/test/X_test.txt',header = FALSE,stringsAsFactors = FALSE,col.names = colnames[,2])
testsubjects <- read.table('UCI HAR Dataset/test/subject_test.txt',header = FALSE,stringsAsFactors = FALSE,col.names = 'subject')
testpred <- read.table('UCI HAR Dataset/test/Y_test.txt',header = FALSE,stringsAsFactors = FALSE,col.names = 'activity')
train <- read.table('UCI HAR Dataset/train/X_train.txt',header = FALSE,stringsAsFactors = FALSE,col.names = colnames[,2])
trainsubjects <- read.table('UCI HAR Dataset/train/subject_train.txt',header = FALSE,stringsAsFactors = FALSE,col.names = 'subject')
trainpred <- read.table('UCI HAR Dataset/train/Y_train.txt',header = FALSE,stringsAsFactors = FALSE,col.names='activity')
test <- as_tibble(test)
test <- add_column(test,subject = testsubjects[,1], activity = testpred[,1],id = 1:2947)
train <- add_column(train, subject = trainsubjects[,1], activity = trainpred[,1])
data <- bind_rows(test,train)
rm(testpred,testsubjects,trainpred,trainsubjects,colnames,test,train)
data <- select(data,c(grep('mean|std',names(data),value = TRUE),subject,activity))
activities <- read.table('UCI HAR Dataset/activity_labels.txt',stringsAsFactors = FALSE)
data$activity <- as.factor(data$activity)
levels(data$activity) <- tolower(activities[,2])
summary <- summarise_all(group_by(data,subject,activity),mean)
write.table(data,file = 'data_set.txt')
write.table(summary,file='summary_data.txt')
